Repository GSG-G11/team3-portfolio, pull requests merged in 2022-01, with the labels that each got.

#7 add index.html and style.css files
  index.html
  style.css
Labels: Done

#8 add HackMd file to README file with all information
  README.md
Labels: Backlog, Awaiting-Review

#14 adding navbar
  alphabet-letters-monogram-icon-logo-260nw-1605361078.jpg
  index.html
  logo.png
  style.css
Labels: Awaiting-Review

#16 9 welcome page
  background-image/background.jpg
  index.html
  style.css
Labels: Done

#15 Add Our Team Section content and style
  imges/logo.61192cf7.svg
  imges/photo.png
  index.html
  style.css
Labels: Awaiting-Review, Done

#17 10 about us page
  index.html
  style.css
Labels: Awaiting-Review

#13 Design protfolio form
  index.html
  style.css
Labels: Awaiting-Review

#19 Add footer
  index.html
  style.css
Labels: Awaiting-Review

#20 2 edit readme
  README.md
Labels: Awaiting-Review

#21 18 general edits
  alphabet-letters-monogram-icon-logo-260nw-1605361078.jpg
  assests/background.jpg
  assests/icon.png
  assests/photo.png
  imges/logo.61192cf7.svg
  index.html
  logo.png
  style.css
Labels: Awaiting-Review

#23 22 general edits 2
  README.md
  index.html
  style.css
Labels: Awaiting-Review

#25 modify code review edits
  style.css
Labels: Awaiting-Review
